spring:
  application:
    name: paper
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
#  session:
#    # todo 取消注释开启分布式 session（须先配置 Redis）
#    # store-type: redis
#    # 30 天过期
#    timeout: 2592000
#  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.151:3306/paper
    username: root
    password: root
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://localhost:9200
#    username: root
#    password: 123456
#  # 文件上传
#  servlet:
#    multipart:
#      # 大小限制
#      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 9902
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# xxl-job
xxl:
  job:
    admin:
      addresses: http://localhost:9903/xxl-job-admin    #admin address for xxl-job
    executor:
      appname: xxl-job-executor-paper-flow    # name shown in xxl-job
      port: 9904                              # address expose to xxl-job
      ip: 127.0.0.1
    accessToken: XJTk_Paper@2023

